/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module add_6 (
    input clk,
    input rst,
    input [7:0] io_dip,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] out,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] holder;
  
  always @* begin
    if (io_dip[0+0-:1] == 1'h0) begin
      holder = a + b;
    end else begin
      holder = a - b;
    end
    out = holder[0+15-:16];
    if (holder == 1'h0) begin
      z = 1'h1;
    end else begin
      z = 1'h0;
    end
    v = ((io_dip[7+0-:1] ^ a[15+0-:1]) & (io_dip[7+0-:1] ^ b[15+0-:1]) & ~holder[15+0-:1]) | (~(io_dip[7+0-:1] ^ a[15+0-:1]) & ~(io_dip[7+0-:1] ^ b[15+0-:1]) & holder[15+0-:1]);
    n = holder[15+0-:1];
  end
endmodule
