/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module cmp_7 (
    input clk,
    input rst,
    input [7:0] io_dip,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] out
  );
  
  
  
  reg [15:0] holder;
  
  always @* begin
    holder = 1'h0;
    
    case (io_dip[1+1-:2])
      1'h1: begin
        holder = {15'h0000, (a == b)};
      end
      2'h2: begin
        holder = {15'h0000, (a < b)};
      end
      2'h3: begin
        holder = {15'h0000, (a <= b)};
      end
    endcase
    out = holder[0+15-:16];
  end
endmodule
