/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module bol_8 (
    input clk,
    input rst,
    input [7:0] io_dip,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    out = 1'h0;
    
    case (io_dip[0+3-:4])
      4'h8: begin
        out = a & b;
      end
      4'he: begin
        out = a | b;
      end
      3'h6: begin
        out = a ^ b;
      end
      4'ha: begin
        out = a;
      end
    endcase
  end
endmodule
