/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mul_10 (
    input clk,
    input rst,
    input [7:0] io_dip,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    out = 1'h0;
    
    case (io_dip[0+1-:2])
      2'h2: begin
        out = a * b;
      end
      2'h3: begin
        out = a / b;
      end
    endcase
  end
endmodule
