/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mulTest_14 (
    input clk,
    input rst,
    input button,
    output reg [15:0] out,
    output reg true
  );
  
  
  
  wire [1-1:0] M_edge_detector_out;
  reg [1-1:0] M_edge_detector_in;
  edge_detector_2 edge_detector (
    .clk(clk),
    .in(M_edge_detector_in),
    .out(M_edge_detector_out)
  );
  localparam BEGIN_state = 4'd0;
  localparam PP1_state = 4'd1;
  localparam PP2_state = 4'd2;
  localparam NN1_state = 4'd3;
  localparam NN2_state = 4'd4;
  localparam PN1_state = 4'd5;
  localparam PN2_state = 4'd6;
  localparam PN3_state = 4'd7;
  localparam GOOD_state = 4'd8;
  localparam ERROR_state = 4'd9;
  
  reg [3:0] M_state_d, M_state_q = BEGIN_state;
  reg [27:0] M_timer_d, M_timer_q = 1'h0;
  wire [16-1:0] M_mul_out;
  reg [8-1:0] M_mul_io_dip;
  reg [16-1:0] M_mul_a;
  reg [16-1:0] M_mul_b;
  mul_10 mul (
    .clk(clk),
    .rst(rst),
    .io_dip(M_mul_io_dip),
    .a(M_mul_a),
    .b(M_mul_b),
    .out(M_mul_out)
  );
  
  localparam PP1A = 16'h70f0;
  
  localparam PP1B = 16'h0003;
  
  localparam PP2A = 16'h00f0;
  
  localparam PP2B = 16'h0003;
  
  localparam NN1A = 16'h8000;
  
  localparam NN1B = 16'hfff8;
  
  localparam NN2A = 16'hffff;
  
  localparam NN2B = 16'hfff8;
  
  localparam PN1A = 16'h00f0;
  
  localparam PN1B = 16'hfff8;
  
  localparam PN2A = 16'h70f0;
  
  localparam PN2B = 16'hfff8;
  
  localparam PN3A = 16'h00f0;
  
  localparam PN3B = 16'h8000;
  
  localparam PP1 = 16'h53d0;
  
  localparam PP2 = 16'h02d0;
  
  localparam NN1 = 16'h0000;
  
  localparam NN2 = 16'h0000;
  
  localparam PN1 = 16'hf880;
  
  localparam PN2 = 16'h7880;
  
  localparam PN3 = 16'h0000;
  
  always @* begin
    M_state_d = M_state_q;
    M_timer_d = M_timer_q;
    
    out = 1'h0;
    M_mul_a = 1'h0;
    M_mul_b = 1'h0;
    M_timer_d = M_timer_q + 1'h1;
    M_mul_io_dip = 8'h02;
    true = 1'h0;
    M_edge_detector_in = button;
    
    case (M_state_q)
      BEGIN_state: begin
        if (M_timer_q[26+1-:2] == 2'h2 & M_edge_detector_out) begin
          M_timer_d = 1'h0;
          M_state_d = PP1_state;
        end
      end
      PP1_state: begin
        M_mul_a = 16'h70f0;
        M_mul_b = 16'h0003;
        if (M_timer_q[26+1-:2] == 1'h0) begin
          out = 16'h70f0;
        end else begin
          if (M_timer_q[26+1-:2] == 1'h1) begin
            out = 16'h0003;
          end else begin
            if (M_timer_q[26+1-:2] == 2'h2) begin
              out = M_mul_out;
            end else begin
              if (M_timer_q[26+1-:2] == 2'h3) begin
                if (M_mul_out == 16'h53d0) begin
                  M_timer_d = 1'h0;
                  M_state_d = PP2_state;
                end else begin
                  M_state_d = ERROR_state;
                end
              end
            end
          end
        end
      end
      PP2_state: begin
        M_mul_a = 16'h00f0;
        M_mul_b = 16'h0003;
        if (M_timer_q[26+1-:2] == 1'h0) begin
          out = 16'h00f0;
        end else begin
          if (M_timer_q[26+1-:2] == 1'h1) begin
            out = 16'h0003;
          end else begin
            if (M_timer_q[26+1-:2] == 2'h2) begin
              out = M_mul_out;
            end else begin
              if (M_timer_q[26+1-:2] == 2'h3) begin
                if (M_mul_out == 16'h02d0) begin
                  M_timer_d = 1'h0;
                  M_state_d = NN1_state;
                end else begin
                  M_state_d = ERROR_state;
                end
              end
            end
          end
        end
      end
      NN1_state: begin
        M_mul_a = 16'h8000;
        M_mul_b = 16'hfff8;
        if (M_timer_q[26+1-:2] == 1'h0) begin
          out = 16'h8000;
        end else begin
          if (M_timer_q[26+1-:2] == 1'h1) begin
            out = 16'hfff8;
          end else begin
            if (M_timer_q[26+1-:2] == 2'h2) begin
              out = M_mul_out;
            end else begin
              if (M_timer_q[26+1-:2] == 2'h3) begin
                if (M_mul_out == 16'h0000) begin
                  M_timer_d = 1'h0;
                  M_state_d = NN2_state;
                end else begin
                  M_state_d = ERROR_state;
                end
              end
            end
          end
        end
      end
      NN2_state: begin
        M_mul_a = 16'hffff;
        M_mul_b = 16'hfff8;
        if (M_timer_q[26+1-:2] == 1'h0) begin
          out = 16'hffff;
        end else begin
          if (M_timer_q[26+1-:2] == 1'h1) begin
            out = 16'hfff8;
          end else begin
            if (M_timer_q[26+1-:2] == 2'h2) begin
              out = M_mul_out;
            end else begin
              if (M_timer_q[26+1-:2] == 2'h3) begin
                if (M_mul_out == 16'h0000) begin
                  M_timer_d = 1'h0;
                  M_state_d = PN1_state;
                end else begin
                  M_state_d = ERROR_state;
                end
              end
            end
          end
        end
      end
      PN1_state: begin
        M_mul_a = 16'h00f0;
        M_mul_b = 16'hfff8;
        if (M_timer_q[26+1-:2] == 1'h0) begin
          out = 16'h00f0;
        end else begin
          if (M_timer_q[26+1-:2] == 1'h1) begin
            out = 16'hfff8;
          end else begin
            if (M_timer_q[26+1-:2] == 2'h2) begin
              out = M_mul_out;
            end else begin
              if (M_timer_q[26+1-:2] == 2'h3) begin
                if (M_mul_out == 16'hf880) begin
                  M_timer_d = 1'h0;
                  M_state_d = PN2_state;
                end else begin
                  M_state_d = ERROR_state;
                end
              end
            end
          end
        end
      end
      PN2_state: begin
        M_mul_a = 16'h70f0;
        M_mul_b = 16'hfff8;
        if (M_timer_q[26+1-:2] == 1'h0) begin
          out = 16'h70f0;
        end else begin
          if (M_timer_q[26+1-:2] == 1'h1) begin
            out = 16'hfff8;
          end else begin
            if (M_timer_q[26+1-:2] == 2'h2) begin
              out = M_mul_out;
            end else begin
              if (M_timer_q[26+1-:2] == 2'h3) begin
                if (M_mul_out == 16'h7880) begin
                  M_timer_d = 1'h0;
                  M_state_d = PN3_state;
                end else begin
                  M_state_d = ERROR_state;
                end
              end
            end
          end
        end
      end
      PN3_state: begin
        M_mul_a = 16'h00f0;
        M_mul_b = 16'h8000;
        if (M_timer_q[26+1-:2] == 1'h0) begin
          out = 16'h00f0;
        end else begin
          if (M_timer_q[26+1-:2] == 1'h1) begin
            out = 16'h8000;
          end else begin
            if (M_timer_q[26+1-:2] == 2'h2) begin
              out = M_mul_out;
            end else begin
              if (M_timer_q[26+1-:2] == 2'h3) begin
                if (M_mul_out == 16'h0000) begin
                  M_timer_d = 1'h0;
                  M_state_d = GOOD_state;
                end else begin
                  M_state_d = ERROR_state;
                end
              end
            end
          end
        end
      end
      GOOD_state: begin
        if (M_timer_q[27+0-:1] == 1'h1) begin
          true = 1'h1;
        end else begin
          if (M_timer_q[25+0-:1] == 1'h1) begin
            out = 16'hff00;
          end else begin
            if (M_timer_q[25+0-:1] == 1'h0) begin
              out = 16'h0000;
            end
          end
        end
      end
      ERROR_state: begin
        if (M_timer_q[25+0-:1] == 1'h1) begin
          out = 16'h00ff;
        end else begin
          out = 16'h0000;
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_timer_q <= 1'h0;
      M_state_q <= 1'h0;
    end else begin
      M_timer_q <= M_timer_d;
      M_state_q <= M_state_d;
    end
  end
  
endmodule
